# Generated by Django 3.0.10 on 2020-11-19 19:16

import ckeditor_uploader.fields
from django.db import migrations, models
import django.utils.timezone
import model_utils.fields
import portxpress.news.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(max_length=500, null=True, verbose_name='Post Title')),
                ('slug', models.SlugField(blank=True, max_length=600, null=True, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=portxpress.news.models.blog_file_path, verbose_name='Upload Info')),
                ('pub_date', models.DateField(null=True, verbose_name='Post Published Date')),
                ('draft', models.BooleanField(default=False)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'ordering': ['title', '-created'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Traffic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(max_length=500, null=True, verbose_name='Post Title')),
                ('slug', models.SlugField(blank=True, max_length=600, null=True, unique=True)),
                ('image', models.FileField(blank=True, null=True, upload_to=portxpress.news.models.blog_file_path, verbose_name='Upload Info')),
                ('pub_date', models.DateField(null=True, verbose_name='Post Published Date')),
                ('draft', models.BooleanField(default=False)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
            options={
                'verbose_name': 'Traffic',
                'verbose_name_plural': 'Traffics',
                'ordering': ['title', '-created'],
                'managed': True,
            },
        ),
    ]
